services:
  - type: web
    name: yt-music-manager-backend
    env: node
    buildCommand: |
      pip install -U yt-dlp
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: YTDL_PATH
        value: yt-dlp
